import Link from 'next/link';
import {signOut} from '@/app/actions';
import {requireAdmin} from '@/lib/security/require-admin';

export default async function Admin(){
 const {supabase:db,user}=await requireAdmin();
 const [{count:properties},{count:vehicles},{count:leads},{count:drafts},{data:recent}]=await Promise.all([
  db.from('listings').select('id',{count:'exact',head:true}).eq('category','property'),
  db.from('listings').select('id',{count:'exact',head:true}).eq('category','vehicle'),
  db.from('enquiries').select('id',{count:'exact',head:true}).eq('status','new'),
  db.from('listings').select('id',{count:'exact',head:true}).eq('status','draft'),
  db.from('listings').select('id,title,status,reference_code,updated_at,category').order('updated_at',{ascending:false}).limit(6),
 ]);
 return <section className="wrap admin-page"><header className="admin-welcome"><div><p className="eyebrow">Evergreen workspace</p><h1>Welcome back.</h1><p>Signed in as {user.email}. Keep property and vehicle inventory up to date from here.</p></div><form action={signOut}><button className="button button-secondary">Sign out</button></form></header>
  <nav className="admin-section-nav" aria-label="Admin sections"><Link aria-current="page" href="/admin">Overview</Link><Link href="/admin/listings?category=property">Properties <b>{properties??0}</b></Link><Link href="/admin/listings?category=vehicle">Vehicles <b>{vehicles??0}</b></Link><Link href="/admin/enquiries">Enquiries <b>{leads??0}</b></Link></nav>
  <div className="admin-stat-grid"><Link className="admin-stat-card property-stat" href="/admin/listings?category=property"><span className="admin-stat-icon" aria-hidden="true">⌂</span><span className="eyebrow">Property</span><strong>{properties??0}</strong><span>Manage homes and rental details <b aria-hidden="true">↗</b></span></Link><Link className="admin-stat-card vehicle-stat" href="/admin/listings?category=vehicle"><span className="admin-stat-icon" aria-hidden="true">◈</span><span className="eyebrow">Vehicles</span><strong>{vehicles??0}</strong><span>Manage cars for sale <b aria-hidden="true">↗</b></span></Link><Link className="admin-stat-card enquiry-stat" href="/admin/enquiries"><span className="admin-stat-icon" aria-hidden="true">↗</span><span className="eyebrow">New enquiries</span><strong>{leads??0}</strong><span>Follow up with people who reached out <b aria-hidden="true">↗</b></span></Link><Link className="admin-stat-card draft-stat" href="/admin/listings"><span className="admin-stat-icon" aria-hidden="true">✎</span><span className="eyebrow">Drafts</span><strong>{drafts??0}</strong><span>Complete details before publishing <b aria-hidden="true">↗</b></span></Link></div>
  <section className="admin-recent" aria-labelledby="recent-heading"><div className="admin-section-heading"><div><p className="eyebrow">Latest activity</p><h2 id="recent-heading">Recently updated</h2></div><Link href="/admin/listings">View inventory <span aria-hidden="true">↗</span></Link></div>{recent?.length?<div className="admin-table-wrap"><table className="admin-table inventory-table"><thead><tr><th>Listing</th><th>Type</th><th>Status</th><th>Updated</th></tr></thead><tbody>{recent.map(item=><tr key={item.id}><td><Link className="inventory-title" href={`/admin/listings/${item.id}/edit`}>{item.title}</Link><small>{item.reference_code}</small></td><td>{item.category==='vehicle'?'Vehicle':'Property'}</td><td><span className={`status-pill status-${item.status}`}>{item.status.replaceAll('_',' ')}</span></td><td>{new Date(item.updated_at).toLocaleDateString('en-NG',{day:'numeric',month:'short',year:'numeric'})}</td></tr>)}</tbody></table></div>:<div className="admin-empty"><h2>Nothing to review yet</h2><p>Start by adding a property or vehicle draft.</p><Link className="button" href="/admin/listings/new">Create a listing</Link></div>}</section>
  <section className="admin-quick-create" aria-label="Create a new listing"><div><p className="eyebrow">Quick start</p><h2>Add to your inventory</h2><p>Start in a focused workflow for the listing type you’re adding.</p></div><div><Link className="button" href="/admin/listings/new?category=property">+ Add property</Link><Link className="button button-secondary" href="/admin/listings/new?category=vehicle">+ Add vehicle</Link></div></section>
 </section>;
}
