import Image from 'next/image';
import Link from 'next/link';
import {formatPrice} from '@/lib/domain/money';
import {resolveFees,type FeeRow} from '@/lib/domain/fees';
import {freshness} from '@/lib/domain/freshness';
import {buildWhatsAppUrl,listingMessage} from '@/lib/domain/whatsapp';
import {formatNaira} from '@/lib/domain/money';
import type {Listing,ListingFee} from '@/lib/types';
import {submitListingReport} from '@/app/actions';
import {ContactEventLink} from '@/components/contact-event-link';
import {normalizePhone} from '@/lib/domain/phone';
import {headers} from 'next/headers';
import {listingStructuredData} from '@/lib/domain/seo';
import {SeoJsonLd} from '@/components/seo-jsonld';

export async function PropertyDetail({listing,canonicalUrl,brand,whatsapp,phone,safetyTips}:{listing:Listing;canonicalUrl:string;brand:string;whatsapp:string|null;phone:string|null;safetyTips:string[]}){
 const requestHeaders=await headers();const jsonLd=listingStructuredData(listing,canonicalUrl,brand);
 const images=[...(listing.listing_images??[])].sort((a,b)=>a.sort_order-b.sort_order);const details=listing.property_details;const amenities=details?.amenities??[];
 const location=[listing.public_location_label||listing.public_location||listing.area,listing.city,listing.state].filter(Boolean).join(', ')||'Nigeria';
 const period=listing.price_period as 'year'|'month'|'day'|'one_time'|null;
 const price=formatPrice({amount:listing.price_amount==null?null:Number(listing.price_amount),period,onRequest:listing.price_on_request,purpose:listing.purpose});
 const active=listing.status==='published'||listing.status==='under_offer';const freshnessLabel=freshness({lastConfirmedAt:listing.last_confirmed_at,staleAfterDays:14});
 const fees=(listing.listing_fees??[]) as ListingFee[];
 const feeRows:FeeRow[]=fees.map(row=>({type:row.fee_type,label:row.label||undefined,state:row.state,amount:row.amount==null?undefined:Number(row.amount),percentOfRent:row.percent_of_rent==null?undefined:Number(row.percent_of_rent),frequency:row.frequency??undefined,refundable:row.refundable??undefined,note:row.note??undefined}));
 const feeResult=resolveFees(listing.price_amount==null?null:{amount:Number(listing.price_amount),period:period==='month'?'month':'year',advanceMonths:details?.advance_rent_months??undefined},feeRows);
 const message=listingMessage({brand,title:listing.title,ref:listing.reference_code,area:listing.area,city:listing.city,priceText:price,url:canonicalUrl});const whatsappUrl=buildWhatsAppUrl({businessNumber:whatsapp,message});const phoneDigits=normalizePhone(phone||'');
 return <article className="wrap detail"><SeoJsonLd data={jsonLd} nonce={requestHeaders.get('x-nonce')||''}/>
  <nav aria-label="Breadcrumb" className="breadcrumbs"><Link href="/">Home</Link><span aria-hidden="true">/</span><Link href={`/property-for-${listing.purpose==='short_let'?'short-let':listing.purpose}`}>{listing.purpose.replace('_',' ')}</Link><span aria-hidden="true">/</span><span>{listing.reference_code}</span></nav>
  <p className="eyebrow">Reference {listing.reference_code} · {listing.purpose.replace('_',' ')}</p>
  <div className="detail-top"><div><h1>{listing.title}</h1><p className="detail-place">{location}</p></div><p className="detail-price">{price}</p></div>
  {!active&&<div className="notice" role="status"><strong>No longer available.</strong> This listing is {listing.status}. <Link href="/recently-closed">See recently closed listings</Link>.</div>}
  {listing.status==='under_offer'&&<p className="notice">Under offer · Contact the realtor to confirm the latest status.</p>}
  <div className="gallery">{images.length?images.slice(0,8).map((image,index)=><div className="gallery-image" key={image.id}><Image src={image.url||''} alt={image.alt_text||listing.title} width={image.width||1400} height={image.height||900} sizes="(max-width: 600px) 100vw, 70vw" unoptimized priority={index===0} loading={index===0?'eager':'lazy'}/></div>):<div className="gallery-image"><div className="gallery-placeholder">Photos coming soon</div></div>}</div>
  <div className="detail-columns"><div><p className="eyebrow">Property details</p><div className="facts-grid">{[['Type',details?.property_type],['Bedrooms',details?.bedrooms],['Bathrooms',details?.bathrooms],['Toilets',details?.toilets],['Furnishing',details?.furnishing],['Advance rent',details?.advance_rent_months?`${details.advance_rent_months} months`:null]].filter(([,value])=>value!==null&&value!==undefined&&value!=='').map(([label,value])=><div key={String(label)}><small>{label}</small><strong>{value}</strong></div>)}</div>
   {listing.purpose!=='sale'&&<section aria-labelledby="fees-title"><h2 id="fees-title">Move-in costs and fees</h2><p>Fees below are supplied by the realtor. Confirm each amount before making payment.</p><ul className="fees">{feeResult.lines.map(line=><li key={`${line.type}-${line.label}`}><span>{line.label}</span><strong>{line.display.kind==='contact'?'Contact for details':line.display.kind==='not_applicable'?'Not applicable':`${formatNaira(line.display.amount)}${line.display.frequency==='month'?' / month':line.display.frequency==='year'?' / year':''}`}</strong></li>)}</ul>{feeResult.rentDueUpfront!==null&&<p>Rent due upfront: <strong>{formatNaira(feeResult.rentDueUpfront)}</strong></p>}{feeResult.upfrontTotal!==null?<p className="fees-total">Estimated upfront total: <strong>{formatNaira(feeResult.upfrontTotal)}</strong></p>:<p className="notice">Contact for details. A full upfront total cannot be calculated from the supplied information.</p>}{feeResult.excludedRecurring.map(item=><p className="muted" key={item}>The total excludes {item}.</p>)}<p className="muted">Based on details confirmed {listing.last_confirmed_at?new Date(listing.last_confirmed_at).toLocaleDateString('en-NG'):'not recently'}. Confirm everything before you pay.</p></section>}
   {listing.purpose==='sale'&&details?.title_type&&<p className="notice">Title type supplied by the realtor: {details.title_type.replaceAll('_',' ')}. Verify documents independently before payment.</p>}
   <h2>About this property</h2><p className="detail-copy">{listing.description||'Ask the realtor for more information about this property.'}</p>
   {amenities.length>0&&<><h2>Features</h2><ul className="features">{amenities.slice(0,24).map((amenity:string)=><li key={amenity}>{amenity.replaceAll('_',' ')}</li>)}</ul></>}
   <h2>Availability</h2><p>{freshnessLabel.kind==='fresh'?`Confirmed available · ${freshnessLabel.days} day${freshnessLabel.days===1?'':'s'} ago`:freshnessLabel.kind==='stale'?`Availability not recently confirmed — please check with ${brand}.`:'No recent availability confirmation is recorded.'}</p>{listing.realtor_inspected_at&&<p>Inspected by the realtor on {new Date(listing.realtor_inspected_at).toLocaleDateString('en-NG')}.</p>}
   <p className="muted">Listing information is supplied by the realtor and has not been independently verified.</p>
   <details className="safety-tips"><summary>Safety tips before you proceed</summary><ul>{(safetyTips.length?safetyTips:['View the property in person before paying.','Verify ownership or the realtor’s authority and review relevant documents.','Confirm all fees and payment instructions directly with the realtor.']).map((tip,index)=><li key={index}>{tip}</li>)}</ul></details>
   {active&&<details><summary>Report this listing or ask if it is still available</summary><form action={submitListingReport} className="form-stack"><input type="hidden" name="listing_reference" value={listing.reference_code}/><input type="hidden" name="listing_slug" value={new URL(canonicalUrl).pathname.split('/').pop()}/><label>Reason<select name="reason" required><option value="no_longer_available">No longer available</option><option value="incorrect_info">Incorrect information</option><option value="suspected_fraud">Suspected fraud</option><option value="marketed_without_consent">Marketed without consent</option><option value="offensive_content">Offensive content</option><option value="other">Other</option></select></label><label>Details (optional)<textarea name="details" maxLength={500}/></label><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><button className="button button-secondary">Send report</button></form></details>}
  </div><aside className="contact-card"><p className="eyebrow">Ask about this listing</p><h2>{brand}</h2><p>Reference <strong>{listing.reference_code}</strong></p>{active&&whatsappUrl?<ContactEventLink className="button" href={whatsappUrl} reference={listing.reference_code} event="whatsapp_click" target="_blank" rel="noopener noreferrer">WhatsApp ↗</ContactEventLink>:<p className="notice">{active?'WhatsApp is not configured yet.':'Contact the realtor for similar listings.'}</p>}{active&&phoneDigits&&<ContactEventLink className="button button-secondary" href={`tel:+${phoneDigits}`} reference={listing.reference_code} event="call_click">Call the realtor</ContactEventLink>}{active&&<Link className="button button-secondary" href={`/contact?listing=${encodeURIComponent(listing.reference_code)}`}>Send an enquiry</Link>}</aside></div>
 </article>;
}
