import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound,permanentRedirect} from 'next/navigation';
import {getListings,getPropertyRouteOptions} from '@/lib/data';
import {parsePropertyRoute} from '@/lib/domain/property-route';
import {parseQuery} from '@/lib/domain/filters';
import {ListingCard} from '@/components/listing-card';

type Params={purposeSlug:string;path?:string[]};type SearchParams=Record<string,string|string[]|undefined>;
async function routeData(params:Promise<Params>){const {purposeSlug,path=[]}=await params;const options=await getPropertyRouteOptions();const result=parsePropertyRoute({purposeSlug,segments:path,knownTypes:options.types.map(t=>t.slug),knownGroups:[...new Set(options.types.map(t=>t.group_slug))],locations:options.locations as Parameters<typeof parsePropertyRoute>[0]['locations']});return {purposeSlug,path,options,result};}
function queryString(params:SearchParams){const search=new URLSearchParams();for(const [key,value] of Object.entries(params))for(const item of Array.isArray(value)?value:[value])if(item!==undefined)search.append(key,item);const value=search.toString();return value?`?${value}`:'';}
export async function generateMetadata({params,searchParams}:{params:Promise<Params>;searchParams:Promise<SearchParams>}):Promise<Metadata>{const data=await routeData(params);if(!data.result.ok)return {title:'Property search not found',robots:{index:false,follow:false}};const search=await searchParams;const {filters}=data.result;const title=`${filters.type||filters.group||'Property'} for ${filters.purpose.replace('_',' ')}${filters.location?.length?` in ${filters.location.map(row=>row.name).join(', ')}`:''}`;const parsed=parseQuery(search).filters;const query:Record<string,string|undefined>={category:'property',purpose:filters.purpose};const types=filters.group?data.options.types.filter(t=>t.group_slug===filters.group).map(t=>t.slug):filters.type?[filters.type]:[];if(types.length)query.property_type=types.join(',');if(filters.bedrooms)query.bedrooms=String(filters.bedrooms);if(filters.feature==='is-serviced')query.serviced='true';if(filters.feature==='is-new')query.new='true';if(filters.feature==='is-furnished')query.furnishing='furnished';const location=filters.location||[];const state=location.find(row=>row.level==='state');const city=location.find(row=>row.level==='city');const area=location.find(row=>row.level==='area'||row.level==='estate');if(state)query.state=state.name;if(city)query.city=city.name;if(area)query.area=area.name;const hasResult=(await getListings(query,1,(parsed.page-1)*12)).length>0;return {title,description:'Browse current property listings. Confirm availability and fees directly with the realtor.',alternates:{canonical:data.result.canonicalPath},robots:Object.keys(search).some(key=>key!=='page')||!hasResult?{index:false,follow:true}:undefined};}
export default async function PropertyLanding({params,searchParams}:{params:Promise<Params>;searchParams:Promise<SearchParams>}){
 const data=await routeData(params);if(!data.result.ok)notFound();const canonical=data.result.canonicalPath;if(`${data.purposeSlug}${data.path.length?`/${data.path.join('/')}`:''}`!==canonical.slice(1))permanentRedirect(`${canonical}${queryString(await searchParams)}`);
 const search=await searchParams;const parsed=parseQuery(search).filters;const filters:Record<string,string|undefined>={category:'property',purpose:data.result.filters.purpose,q:parsed.q,min:parsed.minPrice?.toString(),max:parsed.maxPrice?.toString(),sort:parsed.sort==='newest'?undefined:parsed.sort,bedrooms:parsed.beds?.toString(),bathrooms:parsed.bathrooms?.toString(),furnishing:parsed.furnishing,amenity:parsed.amenities[0]};
 const routeFilters=data.result.filters;const types=routeFilters.group?data.options.types.filter(t=>t.group_slug===routeFilters.group).map(t=>t.slug):routeFilters.type?[routeFilters.type]:[];if(types.length)filters.property_type=types.join(',');
 const location=routeFilters.location||[];const state=location.find(x=>x.level==='state');const city=location.find(x=>x.level==='city');const area=location.find(x=>x.level==='area'||x.level==='estate');if(state)filters.state=state.name;if(city)filters.city=city.name;if(area)filters.area=area.name;
 if(routeFilters.bedrooms)filters.bedrooms=String(routeFilters.bedrooms);if(routeFilters.feature==='is-serviced')filters.serviced='true';if(routeFilters.feature==='is-new')filters.new='true';if(routeFilters.feature==='is-furnished')filters.furnishing='furnished';
 const page=parsed.page;const rows=await getListings(filters,13,(page-1)*12);const hasNext=rows.length>12;const listings=rows.slice(0,12);const label=routeFilters.type?data.options.types.find(t=>t.slug===routeFilters.type)?.slug.replaceAll('_',' '):routeFilters.group?.replaceAll('-',' ');const place=location.map(x=>x.name).join(', ');const title=[label||'Properties',routeFilters.purpose==='rent'?'for rent':routeFilters.purpose==='sale'?'for sale':'for short let',place?`in ${place}`:null].filter(Boolean).join(' ');
 return <section className="wrap text-page"><nav aria-label="Breadcrumb" className="breadcrumbs"><Link href="/">Home</Link><span aria-hidden="true">/</span><span>{title}</span></nav><p className="eyebrow">Property search</p><h1>{title}</h1><p>{listings.length?`${listings.length}${hasNext?'+':''} current listings on this page.`:'No current listings match this search.'} Availability and fees should be confirmed directly with the realtor.</p><form method="GET" className="search-filters"><label>Search<input name="q" defaultValue={parsed.q}/></label><label>Min price (NGN)<input type="number" name="minPrice" min="0" defaultValue={parsed.minPrice}/></label><label>Max price (NGN)<input type="number" name="maxPrice" min="0" defaultValue={parsed.maxPrice}/></label><label>Bathrooms<input type="number" name="bathrooms" min="0" max="30" defaultValue={parsed.bathrooms}/></label><label>Sort<select name="sort" defaultValue={parsed.sort}><option value="newest">Most recent</option><option value="price_asc">Lowest price</option><option value="price_desc">Highest price</option><option value="beds_desc">Most bedrooms</option></select></label><button className="button">Apply filters</button><Link href={canonical}>Clear filters</Link></form>{listings.length?<div className="cards">{listings.map(item=><ListingCard key={item.id} listing={item}/>)}</div>:<div className="empty-state"><h2>Try a wider search</h2><p>Clear a filter or send a property request. The realtor may know about options not currently listed.</p><Link className="button" href="/request">Tell us what you need</Link></div>}<nav className="pagination" aria-label="Search pages">{page>1&&<Link href={`${canonical}?page=${page-1}`}>← Previous</Link>}<span aria-current="page">Page {page}</span>{hasNext&&<Link href={`${canonical}?page=${page+1}`}>Next →</Link>}</nav><p className="muted"><Link href="/request">Can’t find a fit? Send a property request.</Link></p></section>;
}
