import type {Metadata} from 'next';
import {notFound,permanentRedirect} from 'next/navigation';
import {getListingByReference,getPublicSettings} from '@/lib/data';
import {parseRefFromSlug,propertySlug} from '@/lib/domain/slug';
import {PropertyDetail} from '@/components/listings/property-detail';

async function resolve(slug:string){const parsed=parseRefFromSlug(slug);if(!parsed)return null;const listing=await getListingByReference(parsed.reference,'property');if(!listing)return null;const canonicalSlug=propertySlug({title:listing.title,referenceCode:listing.reference_code,beds:listing.property_details?.bedrooms,type:listing.property_details?.property_type,purpose:listing.purpose,area:listing.area,city:listing.city});return {listing,canonicalSlug};}

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const resolved=await resolve(slug);if(!resolved)return {title:'Property listing not found',robots:{index:false,follow:false}};const {listing,canonicalSlug}=resolved;const settings=await getPublicSettings();const brand=settings?.brand_name||'Your Brand';const canonical=`/property/${canonicalSlug}`;const description=[listing.public_location_label||listing.area,listing.city,listing.price_amount?`${listing.currency} ${Number(listing.price_amount).toLocaleString('en-NG')} ${listing.price_period==='year'?'/ year':listing.price_period==='month'?'/ month':''}`:listing.price_on_request?'Price on request':'',listing.description].filter(Boolean).join(' · ').slice(0,160);return {title:`${listing.title} (${listing.reference_code}) | ${brand}`,description,alternates:{canonical},robots:listing.status==='rented'||listing.status==='sold'?{index:false,follow:true}:undefined,openGraph:{title:listing.title,description,url:canonical,type:'article'}};}

export default async function PropertyByReference({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const resolved=await resolve(slug);if(!resolved)notFound();if(slug!==resolved.canonicalSlug)permanentRedirect(`/property/${resolved.canonicalSlug}`);const settings=await getPublicSettings();const origin=process.env.NEXT_PUBLIC_SITE_URL||'http://localhost:3000';return <PropertyDetail listing={resolved.listing} canonicalUrl={`${origin}/property/${resolved.canonicalSlug}`} brand={settings?.brand_name||'Your Brand'} whatsapp={settings?.whatsapp_number||process.env.NEXT_PUBLIC_WHATSAPP_NUMBER||null} phone={settings?.phone||null} safetyTips={Array.isArray(settings?.safety_tips)?settings.safety_tips as string[]:[]}/>;}
