import {requireAdmin} from '@/lib/security/require-admin';
import Link from 'next/link';
import {setListingStatus} from '@/app/actions';
type Status='draft'|'published'|'under_offer'|'rented'|'sold'|'archived';
type SearchParams={category?:string;q?:string;status?:string;error?:string};
export default async function AdminListings({searchParams}:{searchParams:Promise<SearchParams>}){
 const {supabase:db}=await requireAdmin();const search=await searchParams;const category=search.category==='vehicle'?'vehicle':'property';const q=(search.q||'').replace(/[^p{L}p{N} -]/gu,' ').trim().slice(0,80);const status=['draft','published','under_offer','rented','sold','archived'].includes(search.status||'')?search.status as Status:undefined;
 const [{count:propertyCount},{count:vehicleCount}]=await Promise.all([
  db.from('listings').select('id',{count:'exact',head:true}).eq('category','property'),
  db.from('listings').select('id',{count:'exact',head:true}).eq('category','vehicle'),
 ]);
 let query=db.from('listings').select('id,title,status,reference_code,category,updated_at,state,city,area,listing_images(id)').eq('category',category).order('updated_at',{ascending:false}).limit(100);
 if(q)query=query.or(`title.ilike.%${q}%,reference_code.ilike.%${q}%`);if(status)query=query.eq('status',status);
 const {data:list}=await query;const title=category==='property'?'Properties':'Vehicles';const base=`/admin/listings?category=${category}`;
 return <section className="wrap admin-page"><header className="page-heading"><p className="eyebrow">Inventory · {propertyCount??0} properties · {vehicleCount??0} vehicles</p><h1>{title}</h1><p>Keep property and vehicle inventory in separate workspaces. Drafts remain private until you publish them.</p></header>{search.error&&<p className="notice" role="alert">{search.error==='publication-migration'?'Supabase is still enforcing the older publishing checklist. Apply migration 202610100001_minimal_listing_publication.sql, then try again.':search.error==='publication-details'?'Supabase could not find this listing’s property or vehicle details. Open the listing, save its details and try again.':search.error==='readiness'?'Supabase refused the status change. Confirm that at least one photo is uploaded and selected as the cover; if that is already true, check the applied migrations.':'The listing status could not be changed.'}</p>}
  <nav className="admin-quick-links" aria-label="Admin navigation"><Link href="/admin">Overview</Link><Link href="/admin/enquiries">Enquiries</Link><Link href="/admin/settings">Settings</Link></nav><div className="admin-section-nav" aria-label="Inventory type"><Link aria-current={category==='property'?'page':undefined} href="/admin/listings?category=property"><span>Properties</span><b>{propertyCount??0}</b></Link><Link aria-current={category==='vehicle'?'page':undefined} href="/admin/listings?category=vehicle"><span>Vehicles</span><b>{vehicleCount??0}</b></Link></div>
  <div className="inventory-toolbar"><form method="GET" action="/admin/listings" className="inventory-search"><input type="hidden" name="category" value={category}/><label htmlFor="listing-search">Search {category==='property'?'properties':'vehicles'}</label><input id="listing-search" name="q" type="search" defaultValue={q} placeholder="Title or reference"/><label htmlFor="listing-status">Status</label><select id="listing-status" name="status" defaultValue={status||''}><option value="">All statuses</option><option value="draft">Draft</option><option value="published">Published</option><option value="under_offer">Under offer</option><option value="rented">Rented</option><option value="sold">Sold</option><option value="archived">Archived</option></select><button className="button">Apply</button><Link className="toolbar-clear" href={base}>Reset</Link></form><Link className="button" href="/admin/listings/new">+ Add {category}</Link></div>
  <div className="inventory-summary"><span><strong>{list?.length??0}</strong> {list?.length===1?'listing':'listings'}{(list?.length??0)>=100?' · first 100 shown':''}</span><span>{status?`Filtered by ${status.replaceAll('_',' ')}`:'Recently updated first'}</span></div>
  {list?.length?<div className="admin-table-wrap"><table className="admin-table inventory-table"><thead><tr><th>Listing</th><th>Reference</th><th>Location</th><th>Status</th><th>Updated</th><th>Change status</th></tr></thead><tbody>{list.map(item=>{const photoCount=Array.isArray(item.listing_images)?item.listing_images.length:0;return <tr key={item.id}><td><Link className="inventory-title" href={`/admin/listings/${item.id}/edit`}>{item.title}</Link><small>{photoCount} {photoCount===1?'photo':'photos'}</small></td><td>{item.reference_code}</td><td>{[item.area,item.city,item.state].filter(Boolean).join(', ')||'Location not set'}</td><td><span className={`status-pill status-${item.status}`}>{item.status.replaceAll('_',' ')}</span></td><td>{new Date(item.updated_at).toLocaleDateString('en-NG',{day:'numeric',month:'short',year:'numeric'})}</td><td><form action={setListingStatus} className="status-update-form"><input type="hidden" name="id" value={item.id}/><select name="status" defaultValue={item.status} aria-label={`Status for ${item.title}`}><option value={item.status}>{item.status.replaceAll('_',' ')}</option>{statusChoices(item.status).filter(([value])=>value!==item.status).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button className="text-button">Save</button></form></td></tr>})}</tbody></table></div>:<div className="admin-empty"><span aria-hidden="true">{category==='property'?'⌂':'◈'}</span><h2>{q||status?'No matching listings':'No '+title.toLowerCase()+' yet'}</h2><p>{q||status?'Try a broader search or clear the current filters.':`Create a ${category} draft to start building this part of your inventory.`}</p>{q||status?<Link className="button button-secondary" href={base}>Clear filters</Link>:<Link className="button" href={`/admin/listings/new?category=${category}`}>Add first {category}</Link>}</div>}
 </section>;
}
function statusChoices(status:string):[string,string][]{const labels:Record<string,string>={draft:'Draft',published:'Published',under_offer:'Under offer',rented:'Rented',sold:'Sold',archived:'Archived'};const choices:Record<string,string[]>={draft:['draft','published','archived'],published:['published','under_offer','rented','sold','archived','draft'],under_offer:['under_offer','published','rented','sold','archived'],rented:['rented','archived'],sold:['sold','archived'],archived:['archived','draft']};return (choices[status]||['draft']).map(value=>[value,labels[value]]);}
