'use client';
import {useEffect,useRef,useState,useTransition,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import {uploadListingImages} from '@/app/actions';

function toBlob(canvas:HTMLCanvasElement,type:string,quality:number){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('This browser could not encode the photo.')),type,quality));}
async function encodeImage(file:File,maxEdge:number,quality:number){
 const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});const ratio=Math.min(1,maxEdge/Math.max(bitmap.width,bitmap.height));let width=Math.max(1,Math.round(bitmap.width*ratio));let height=Math.max(1,Math.round(bitmap.height*ratio));const canvas=document.createElement('canvas');const context=canvas.getContext('2d');if(!context)throw new Error('Photo processing is unavailable in this browser.');let blob:Blob|undefined;let type='image/webp';
 for(let resize=0;resize<4;resize++){canvas.width=width;canvas.height=height;context.drawImage(bitmap,0,0,width,height);for(const q of [quality,.68,.56,.44]){blob=await toBlob(canvas,'image/webp',q);type='image/webp';if(blob.type!=='image/webp'){blob=await toBlob(canvas,'image/jpeg',q);type='image/jpeg';}if(blob&&blob.size<=2*1024*1024)break;}if(blob&&blob.size<=2*1024*1024)break;width=Math.max(1,Math.round(width*.8));height=Math.max(1,Math.round(height*.8));}
 bitmap.close();if(!blob||blob.size>2*1024*1024)throw new Error('Could not compress this image below 2 MB. Choose a smaller photo.');return {blob,width,height,type};
}
export function ImageUploadForm({listingId,remaining}:{listingId:string;remaining:number}){
 const input=useRef<HTMLInputElement>(null);const previewUrls=useRef<string[]>([]);const router=useRouter();const [busy,startTransition]=useTransition();const [files,setFiles]=useState<File[]>([]);const [previews,setPreviews]=useState<Array<{file:File;url:string}>>([]);const [progress,setProgress]=useState(0);const [message,setMessage]=useState('');const [errors,setErrors]=useState<string[]>([]);
 useEffect(()=>()=>previewUrls.current.forEach(url=>URL.revokeObjectURL(url)),[]);
 function replaceFiles(next:File[]){previewUrls.current.forEach(url=>URL.revokeObjectURL(url));previewUrls.current=[];setFiles(next);setPreviews(next.map(file=>{const url=URL.createObjectURL(file);previewUrls.current.push(url);return {file,url};}));}
 function choose(selected:FileList|null){setMessage('');setErrors([]);const chosen=Array.from(selected||[]).slice(0,Math.max(0,remaining));if(selected&&selected.length>chosen.length)setMessage(`This listing has room for ${remaining} more photo${remaining===1?'':'s'}.`);replaceFiles(chosen);setProgress(0);}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!files.length){setMessage('Choose one or more photos first.');return;}const oversize=files.filter(file=>file.size>15*1024*1024);if(oversize.length){setErrors(oversize.map(file=>`${file.name}: original image exceeds 15 MB.`));return;}const altText=String(new FormData(event.currentTarget).get('alt_text')||'').trim();if(!altText){setMessage('Describe what is visible in the photos.');return;}setMessage('');setErrors([]);setProgress(0);
  startTransition(async()=>{let uploaded=0;const failed:string[]=[];for(const [index,file] of files.entries()){try{const display=await encodeImage(file,1600,.8);const thumb=await encodeImage(file,480,.8);const blurCanvas=document.createElement('canvas');blurCanvas.width=10;blurCanvas.height=10;const blurContext=blurCanvas.getContext('2d');if(!blurContext)throw new Error('Photo processing is unavailable.');const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});blurContext.drawImage(bitmap,0,0,10,10);bitmap.close();const blur=blurCanvas.toDataURL('image/webp',.35);if(blur.length>2048)throw new Error('Could not create a small photo preview.');
    const data=new FormData();data.set('id',listingId);data.set('alt_text',altText);data.set('display',new File([display.blob],`display.${display.type==='image/webp'?'webp':'jpg'}`,{type:display.type}));data.set('thumb',new File([thumb.blob],`thumb.${thumb.type==='image/webp'?'webp':'jpg'}`,{type:thumb.type}));data.set('width',String(display.width));data.set('height',String(display.height));data.set('blur_data_url',blur);const result=await uploadListingImages(data);if(!result.ok)throw new Error(result.error==='photo-limit'?'Listing photo limit reached.':result.error==='upload'?'Storage upload failed.':'Could not save this photo.');uploaded++;
   }catch(error){failed.push(`${file.name}: ${error instanceof Error?error.message:'could not be processed'}`);}setProgress(index+1);}
   replaceFiles([]);if(input.current)input.current.value='';setErrors(failed);setMessage(uploaded?`${uploaded} photo${uploaded===1?'':'s'} uploaded${failed.length?`; ${failed.length} could not be added`:'.'}`:'No photos were uploaded.');if(uploaded)router.refresh();
  });
 }
 return <form onSubmit={submit} encType="multipart/form-data" className="image-upload-form"><div className="image-upload-fields"><div className="image-dropzone"><input ref={input} id={`photos-${listingId}`} type="file" accept="image/jpeg,image/png,image/webp" multiple required disabled={busy||remaining===0} onChange={event=>choose(event.currentTarget.files)}/><label htmlFor={`photos-${listingId}`}><span className="upload-icon" aria-hidden="true">↑</span><strong>{remaining===0?'Photo limit reached':'Choose photos to upload'}</strong><span>JPG, PNG or WebP · up to 15 MB each</span><span className="upload-pick">Browse files</span></label></div><div className="field photo-alt-field"><label htmlFor={`alt-${listingId}`}>Photo description</label><input id={`alt-${listingId}`} name="alt_text" required maxLength={200} placeholder="Describe what’s visible" disabled={busy||remaining===0}/><small>Use one accurate description for the selected batch. Add images that show the property or vehicle clearly.</small></div></div>
  {previews.length>0&&<div className="upload-queue" aria-label={`${files.length} selected photos`}>{previews.map(({file,url},index)=><div className="upload-queue-item" key={`${file.name}-${file.lastModified}-${index}`}><span role="img" aria-label={`Preview: ${file.name}`} className="upload-preview" style={{backgroundImage:`url("${url}")`}}/><span><strong>{file.name}</strong><small>{(file.size/1024/1024).toFixed(1)} MB · {progress>index?'Uploaded':busy&&progress===index?'Processing…':'Ready'}</small></span></div>)}</div>}
  {busy&&<div className="upload-progress" role="status" aria-live="polite"><span style={{width:`${files.length?progress/files.length*100:0}%`}}/><small>Preparing and uploading {progress} of {files.length} photos…</small></div>}{message&&<p className="notice" role={errors.length?'alert':'status'}>{message}</p>}{errors.length>0&&<ul className="upload-errors">{errors.map(error=><li key={error}>{error}</li>)}</ul>}
  <div className="upload-submit-row"><button className="button" disabled={busy||remaining===0||files.length===0}>{busy?'Uploading photos…':`Upload ${files.length||''} photo${files.length===1?'':'s'}`}</button><span className="muted">{remaining} upload{remaining===1?'':'s'} remaining</span></div>
 </form>;
}
