import {saveListing} from '@/app/actions';
import type {Listing,ListingFee,PropertyDetails,VehicleDetails} from '@/lib/types';
import {VehicleCatalogFields} from '@/components/admin/vehicle-catalog-fields';
export type LocationOption={id:string;parent_id:string|null;level:string;name:string;slug:string};
export type PropertyTypeOption={slug:string;label:string;group_slug:string};
export function ListingFields({listing,property,vehicle,privateData,locations,types,shortLetEnabled,category}:{listing?:Listing;property?:PropertyDetails|null;vehicle?:VehicleDetails|null;privateData?:{exact_address?:string|null;owner_name?:string|null;owner_phone?:string|null;vin?:string|null;internal_notes?:string|null}|null;locations:LocationOption[];types:PropertyTypeOption[];shortLetEnabled:boolean;category:'property'|'vehicle'}){
 const locationNames=new Map(locations.map(location=>[location.id,location]));
 const locationLabel=(location:LocationOption)=>{const chain=[location];let parent=location.parent_id?locationNames.get(location.parent_id):undefined;while(parent){chain.unshift(parent);parent=parent.parent_id?locationNames.get(parent.parent_id):undefined;}return chain.map(row=>row.name).join(' · ');};
 const fees=new Map((listing?.listing_fees||[]).map(fee=>[fee.fee_type,fee]));
 const period=listing?.price_on_request?'price_on_request':listing?.price_period||(category==='vehicle'?'one_time':'year');
 return <form action={saveListing} className="listing-form">
  <p className="notice">Quick publish needs a title and one photo. Price, location, description, property or vehicle facts, availability confirmation, fees, and photo description can be added later.</p>
  <input type="hidden" name="category" value={category}/>
  {listing&&<><input type="hidden" name="id" value={listing.id}/><input type="hidden" name="slug" value={listing.slug}/><input type="hidden" name="reference_code" value={listing.reference_code}/></>}
  <fieldset><legend>Essentials</legend>
   <div className="field"><label htmlFor="purpose">Purpose</label>{category==='vehicle'?<><input type="hidden" name="purpose" value="sale"/><p className="field-static">Vehicle · For sale</p></>:<select id="purpose" name="purpose" defaultValue={listing?.purpose||'rent'}><option value="rent">For rent</option><option value="sale">For sale</option>{shortLetEnabled&&<option value="short_let">Short let</option>}</select>}</div>
   <div className="field"><label htmlFor="title">Listing title</label><input id="title" name="title" required minLength={5} maxLength={140} defaultValue={listing?.title||''}/></div>
   <div className="field"><label htmlFor="description">Description <span className="muted">(optional)</span></label><textarea id="description" name="description" maxLength={5000} defaultValue={listing?.description||''}/></div>
   <div className="field"><label htmlFor="price_amount">Price (NGN) <span className="muted">(optional)</span></label><input id="price_amount" name="price_amount" type="number" min="0" step="1" defaultValue={listing?.price_amount??''}/><small>Leave blank to show “Price on request”.</small></div>
   <div className="field"><label htmlFor="price_period">Price period</label><select id="price_period" name="price_period" defaultValue={period}><option value="price_on_request">Price on request</option>{category==='property'&&<><option value="year">Per year</option><option value="month">Per month</option><option value="day">Per night</option></>}<option value="one_time">One-time price</option></select></div>
   <div className="field"><label htmlFor="location_id">City or neighbourhood <span className="muted">(optional)</span></label><select id="location_id" name="location_id" defaultValue={listing?.location_id||''}><option value="">Choose an area</option>{locations.map(location=><option key={location.id} value={location.id}>{locationLabel(location)}</option>)}</select><small>Add a location when known.</small></div>
   <div className="field"><label htmlFor="public_location_label">Public location label (optional)</label><input id="public_location_label" name="public_location_label" maxLength={120} defaultValue={listing?.public_location_label||''} placeholder="Example: near the waterfront"/></div>
  </fieldset>
  {category==='property'&&<><fieldset><legend>Property details</legend>
   <div className="field"><label htmlFor="property_type">Property type <span className="muted">(optional)</span></label><select id="property_type" name="property_type" defaultValue={property?.property_type||''}><option value="">Choose a property type</option>{types.map(type=><option key={type.slug} value={type.slug}>{type.label}</option>)}</select></div>
   <div className="field"><label htmlFor="bedrooms">Bedrooms</label><input id="bedrooms" name="bedrooms" type="number" min="0" max="30" defaultValue={property?.bedrooms??''}/></div>
   <div className="field"><label htmlFor="bathrooms">Bathrooms</label><input id="bathrooms" name="bathrooms" type="number" min="0" max="30" defaultValue={property?.bathrooms??''}/></div>
   <div className="field"><label htmlFor="furnishing">Furnishing</label><select id="furnishing" name="furnishing" defaultValue={property?.furnishing||''}><option value="">Unspecified</option><option value="furnished">Furnished</option><option value="semi_furnished">Semi-furnished</option><option value="unfurnished">Unfurnished</option></select></div>
   <div className="field"><label htmlFor="advance_rent_months">Advance rent months (monthly rent only)</label><input id="advance_rent_months" name="advance_rent_months" type="number" min="1" max="36" defaultValue={property?.advance_rent_months??''}/></div>
   <div className="field"><label htmlFor="amenities">Amenities (comma-separated keys)</label><input id="amenities" name="amenities" maxLength={500} defaultValue={property?.amenities?.join(', ')||''} placeholder="parking_space, standby_generator, security_24h"/><small>Use only features that are present and approved.</small></div>
   <div className="field"><label htmlFor="title_type">Title type</label><select id="title_type" name="title_type" defaultValue={property?.title_type||''}><option value="">Unspecified</option>{[['c_of_o','Certificate of Occupancy'],['governors_consent',"Governor's Consent"],['deed_of_assignment','Deed of Assignment'],['registered_survey','Registered survey'],['excision','Excision'],['gazette','Gazette'],['other','Other'],['unknown','Unknown']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>
  </fieldset>
  <fieldset><legend>Rental fees and upfront costs</legend><p>Each fee is known, not applicable, or still unknown. Unknown required fees prevent publishing unless you acknowledge them.</p>
   <FeeEditor id="agent_fee" label="Agency fee" amount={property?.agent_fee} fee={fees.get('agency')} stateName="fee_agency_state"/>
   <FeeEditor id="agreement_fee" label="Agreement/legal fee" amount={(Number(property?.agreement_fee||0)+Number(property?.legal_fee||0))||null} fee={fees.get('agreement_legal')} stateName="fee_agreement_legal_state"/>
   <FeeEditor id="caution_fee" label="Caution deposit" amount={property?.caution_fee} fee={fees.get('caution_deposit')} stateName="fee_caution_state"/>
   <FeeEditor id="service_charge" label="Service charge" amount={property?.service_charge} fee={fees.get('service_charge')} stateName="fee_service_state"/>
   <div className="field"><label htmlFor="fee_service_frequency">Service charge frequency</label><select id="fee_service_frequency" name="fee_service_frequency" defaultValue={fees.get('service_charge')?.frequency||'year'}><option value="year">Annual</option><option value="month">Monthly (excluded from upfront total)</option><option value="one_time">One-time</option></select></div>
   <p className="muted">Fees are optional. If you leave them blank, visitors will be asked to contact you for details.</p>
  </fieldset></>}
  {category==='vehicle'&&<fieldset><legend>Vehicle details</legend>
   <VehicleCatalogFields make={vehicle?.make||''} model={vehicle?.model||''} year={vehicle?.year??null} vehicleClass={vehicle?.vehicle_class||null}/>
   <div className="field"><label htmlFor="mileage">Mileage</label><input id="mileage" name="mileage" type="number" min="0" defaultValue={vehicle?.mileage??''}/></div>
   <div className="field"><label htmlFor="condition">Condition</label><select id="condition" name="condition" defaultValue={vehicle?.condition||''}><option value="">Choose one</option><option value="new">New</option><option value="used">Used</option></select></div>
   <div className="field"><label htmlFor="import_status">Import status</label><select id="import_status" name="import_status" defaultValue={vehicle?.import_status||''}><option value="">Choose one</option><option value="brand_new">Brand new</option><option value="foreign_used">Foreign used</option><option value="nigerian_used">Nigerian used</option></select></div>
   <div className="field"><label htmlFor="transmission">Transmission</label><select id="transmission" name="transmission" defaultValue={vehicle?.transmission||''}><option value="">Unspecified</option><option value="automatic">Automatic</option><option value="manual">Manual</option><option value="cvt">CVT</option><option value="other">Other</option></select></div>
   <div className="field"><label htmlFor="fuel_type">Fuel</label><select id="fuel_type" name="fuel_type" defaultValue={vehicle?.fuel_type||''}><option value="">Unspecified</option><option value="petrol">Petrol</option><option value="diesel">Diesel</option><option value="hybrid">Hybrid</option><option value="electric">Electric</option><option value="cng">CNG</option><option value="other">Other</option></select></div>
   <div className="field"><label htmlFor="colour">Colour</label><input id="colour" name="colour" maxLength={40} defaultValue={vehicle?.colour||''}/></div>
  </fieldset>}
  <details><summary>Private information and advanced fields</summary><fieldset><legend>Private fields (never displayed publicly)</legend><div className="field"><label htmlFor="exact_address">Exact address</label><input id="exact_address" name="exact_address" maxLength={240} defaultValue={privateData?.exact_address||''}/></div><div className="field"><label htmlFor="owner_name">Owner name</label><input id="owner_name" name="owner_name" maxLength={120} defaultValue={privateData?.owner_name||''}/></div><div className="field"><label htmlFor="owner_phone">Owner phone</label><input id="owner_phone" name="owner_phone" maxLength={32} defaultValue={privateData?.owner_phone||''}/></div>{category==='vehicle'&&<div className="field"><label htmlFor="vin">Vehicle VIN (private)</label><input id="vin" name="vin" maxLength={40} defaultValue={privateData?.vin||''}/></div>}<div className="field"><label htmlFor="internal_notes">Internal notes</label><textarea id="internal_notes" name="internal_notes" maxLength={2000} defaultValue={privateData?.internal_notes||''}/></div></fieldset><div className="field"><label htmlFor="relist_note">Relist note (required when relisting rented/sold inventory)</label><input id="relist_note" name="relist_note" maxLength={500}/></div></details>
  {listing?<><div className="field"><label htmlFor="status">Status</label><select id="status" name="status" defaultValue={listing.status}>{statusChoices(listing.status).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>
  <div className="field"><label htmlFor="last_confirmed_at">Availability confirmed (only set after checking)</label><input id="last_confirmed_at" name="last_confirmed_at" type="date" defaultValue={listing.last_confirmed_at?.slice(0,10)||''}/></div></>:<input type="hidden" name="status" value="draft"/>}
  <button className="button">{listing?'Save changes':'Save draft & continue to photos'}</button>
 </form>;
}
function statusChoices(status:string):[string,string][]{const labels:Record<string,string>={draft:'Draft',published:'Published',under_offer:'Under offer',rented:'Rented',sold:'Sold',archived:'Archived'};const choices:Record<string,string[]>={draft:['draft','published','archived'],published:['published','under_offer','rented','sold','archived','draft'],under_offer:['under_offer','published','rented','sold','archived'],rented:['rented','published','archived'],sold:['sold','published','archived'],archived:['archived','draft']};return (choices[status]||['draft']).map(value=>[value,labels[value]]);}
function FeeEditor({id,label,amount,fee,stateName}:{id:string;label:string;amount:number|null|undefined;fee?:ListingFee;stateName:string}){
 return <div className="fee-editor"><div className="field"><label htmlFor={`${id}_state`}>{label} status</label><select id={`${id}_state`} name={stateName} defaultValue={fee?.state|| (amount!=null?'known':'unknown')}><option value="known">Known amount</option><option value="not_applicable">Not applicable</option><option value="unknown">Contact for details</option></select></div><div className="field"><label htmlFor={id}>{label} (NGN)</label><input id={id} name={id} type="number" min="0" step="1" defaultValue={amount??fee?.amount??''}/></div></div>;
}
