import Image from 'next/image';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { getListing,getListings } from '@/lib/data';
import { formatPrice, whatsAppUrl } from '@/lib/format';
import { ListingCard } from '@/components/listing-card';
import {vehicleClassLabel} from '@/lib/domain/vehicle-catalog';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const item=await getListing(slug,'vehicle');if(!item)return {title:'Vehicle not found',robots:{index:false}};return {title:item.title,description:`${item.title} for sale · ${formatPrice(item.price_amount,item.currency,item.price_period)}`,alternates:{canonical:'/cars/'+item.slug},openGraph:{title:item.title,description:item.description.slice(0,160),type:'article',images:item.listing_images?.filter(image=>image.is_cover).map(image=>({url:image.url||''})).filter(image=>image.url)}};}
export default async function CarDetail({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;const item=await getListing(slug,'vehicle');if(!item)notFound();const images=(item.listing_images||[]).filter(image=>image.url).sort((a,b)=>a.sort_order-b.sort_order);const d=item.vehicle_details;const location=[item.area,item.city,item.state].filter(Boolean).join(', ')||'Location available on request';const url=whatsAppUrl(process.env.NEXT_PUBLIC_WHATSAPP_NUMBER,item,'ask about this vehicle');const related=await getListings({category:'vehicle',city:item.city||undefined},3,0,item.id);
  return <article className="wrap detail"><p className="eyebrow">{item.reference_code} · Vehicle for sale</p><div className="detail-top"><div><h1>{item.title}</h1><p className="detail-place">{location}</p></div><p className="detail-price">{formatPrice(item.price_amount,item.currency,item.price_period)}</p></div><div className="gallery">{images.length?images.slice(0,5).map(i=><div className="gallery-image" key={i.id}><Image src={i.url||''} alt={i.alt_text||item.title} width={1400} height={900} sizes="(max-width: 600px) 100vw, 70vw" unoptimized loading="lazy"/></div>):<div className="gallery-image"><div className="gallery-placeholder">Photos coming soon</div></div>}</div><div className="detail-columns"><div><div className="facts-grid">{[['Vehicle type',vehicleClassLabel(d?.vehicle_class)],['Year',d?.year],['Make',d?.make],['Model',d?.model],['Condition',d?.condition],['Import status',d?.import_status],['Transmission',d?.transmission],['Mileage',d?.mileage],['Fuel',d?.fuel_type],['Colour',d?.colour]].filter(([,v])=>v!=null&&v!=='').map(([k,v])=><div key={String(k)}><small>{k}</small><strong>{v}</strong></div>)}</div>{!d?.year&&!d?.make&&!d?.model&&!d?.condition&&!d?.import_status&&!d?.transmission&&!d?.mileage&&!d?.fuel_type&&!d?.colour&&!d?.vehicle_class&&<p className="muted">More vehicle details are available on request.</p>}<h2>Vehicle details</h2><p className="detail-copy">{item.description||'Ask the realtor for more information, documentation and inspection arrangements.'}</p><p className="muted">Please confirm availability and inspect the vehicle before proceeding. This listing has not been independently verified.</p></div><aside className="contact-card"><p className="eyebrow">Ask about this vehicle</p><p>Reference <strong>{item.reference_code}</strong></p>{url?<a className="button" href={url} target="_blank" rel="noopener noreferrer">Enquire on WhatsApp ↗</a>:<p className="notice">WhatsApp contact is not configured yet.</p>}<a className="button" href={`/contact?listing=${encodeURIComponent(item.reference_code)}`}>Send an enquiry</a></aside></div>{related.length>0&&<section className="section"><div className="section-head"><h2>More vehicles nearby</h2></div><div className="cards">{related.map(listing=><ListingCard key={listing.id} listing={listing}/>)}</div></section>}</article>
}
