export type Json=string|number|boolean|null|{[key:string]:Json|undefined}|Json[];
type Relation={foreignKeyName:string;columns:string[];isOneToOne:boolean;referencedRelation:string;referencedColumns:string[]};
type Table<Row extends Record<string,unknown>,Insert extends Record<string,unknown>,Update extends Record<string,unknown>=Partial<Insert>,Relationships extends Relation[]=[]>= {Row:Row;Insert:Insert;Update:Update;Relationships:Relationships};
export type Database={public:{Tables:{
  profiles:Table<{id:string;display_name:string|null;phone:string|null;whatsapp_number:string|null;email:string|null;bio:string|null;avatar_path:string|null;service_areas:Json;role:'admin';created_at:string;updated_at:string},{id:string;display_name?:string|null;phone?:string|null;whatsapp_number?:string|null;email?:string|null;bio?:string|null;avatar_path?:string|null;service_areas?:Json;role?:'admin'}>;
  listings:Table<{id:string;is_demo:boolean;slug:string;reference_code:string;category:'property'|'vehicle';purpose:'rent'|'sale'|'short_let';title:string;description:string;price_amount:number|null;currency:string;price_period:'year'|'month'|'day'|'one_time'|'price_on_request';negotiable:boolean;state:string|null;city:string|null;area:string|null;public_location:string|null;status:'draft'|'published'|'under_offer'|'rented'|'sold'|'archived'|'unavailable';featured:boolean;available_from:string|null;last_confirmed_at:string|null;published_at:string|null;created_by:string;created_at:string;updated_at:string},{is_demo?:boolean;slug:string;reference_code:string;category:'property'|'vehicle';purpose:'rent'|'sale'|'short_let';title:string;price_period:'year'|'month'|'day'|'one_time'|'price_on_request';created_by:string;id?:string;description?:string;price_amount?:number|null;currency?:string;negotiable?:boolean;state?:string|null;city?:string|null;area?:string|null;public_location?:string|null;status?:'draft'|'published'|'under_offer'|'rented'|'sold'|'archived'|'unavailable';featured?:boolean;available_from?:string|null;last_confirmed_at?:string|null;published_at?:string|null;created_at?:string;updated_at?:string},Partial<{is_demo?:boolean;slug:string;reference_code:string;category:'property'|'vehicle';purpose:'rent'|'sale'|'short_let';title:string;price_period:'year'|'month'|'day'|'one_time'|'price_on_request';created_by:string;description:string;price_amount:number|null;currency:string;negotiable:boolean;state:string|null;city:string|null;area:string|null;public_location:string|null;status:'draft'|'published'|'under_offer'|'rented'|'sold'|'archived'|'unavailable';featured:boolean;available_from:string|null;last_confirmed_at:string|null;published_at:string|null;updated_at:string}>,[{foreignKeyName:'listings_created_by_fkey';columns:['created_by'];isOneToOne:false;referencedRelation:'profiles';referencedColumns:['id']}]>;
  listing_private:Table<{listing_id:string;exact_address:string|null;show_exact_address:boolean},{listing_id:string;exact_address?:string|null;show_exact_address?:boolean}>;
  property_details:Table<{listing_id:string;property_type:string;bedrooms:number|null; bathrooms:number|null;toilets:number|null;furnishing:string|null;parking_spaces:number|null;area_amount:number|null;area_unit:string|null;rent_payment_frequency:string|null;agent_fee:number|null;agreement_fee:number|null;legal_fee:number|null;caution_fee:number|null;service_charge:number|null;amenities:Json},{listing_id:string;property_type:string;bedrooms?:number|null;bathrooms?:number|null;toilets?:number|null;furnishing?:string|null;parking_spaces?:number|null;area_amount?:number|null;area_unit?:string|null;rent_payment_frequency?:string|null;agent_fee?:number|null;agreement_fee?:number|null;legal_fee?:number|null;caution_fee?:number|null;service_charge?:number|null;amenities?:Json},Partial<{listing_id:string;property_type:string;bedrooms:number|null;bathrooms:number|null;toilets:number|null;furnishing:string|null;parking_spaces:number|null;area_amount:number|null;area_unit:string|null;rent_payment_frequency:string|null;agent_fee:number|null;agreement_fee:number|null;legal_fee:number|null;caution_fee:number|null;service_charge:number|null;amenities:Json}>,[{foreignKeyName:'property_details_listing_id_fkey';columns:['listing_id'];isOneToOne:true;referencedRelation:'listings';referencedColumns:['id']}]>;
  vehicle_details:Table<{listing_id:string;make:string;model:string;trim:string|null;year:number|null;mileage:number|null;mileage_unit:string|null;condition:string|null;import_status:string|null;transmission:string|null;fuel_type:string|null;body_type:string|null;engine_size:string|null;colour:string|null;known_issues:string|null},{listing_id:string;make:string;model:string;trim?:string|null;year?:number|null;mileage?:number|null;mileage_unit?:string|null;condition?:string|null;import_status?:string|null;transmission?:string|null;fuel_type?:string|null;body_type?:string|null;engine_size?:string|null;colour?:string|null;known_issues?:string|null},Partial<{listing_id:string;make:string;model:string;trim:string|null;year:number|null;mileage:number|null;mileage_unit:string|null;condition:string|null;import_status:string|null;transmission:string|null;fuel_type:string|null;body_type:string|null;engine_size:string|null;colour:string|null;known_issues:string|null}>,[{foreignKeyName:'vehicle_details_listing_id_fkey';columns:['listing_id'];isOneToOne:true;referencedRelation:'listings';referencedColumns:['id']}]>;
  listing_images:Table<{id:string;listing_id:string;storage_path:string;alt_text:string;sort_order:number;is_cover:boolean;created_at:string},{listing_id:string;storage_path:string;alt_text?:string;sort_order?:number;is_cover?:boolean;id?:string;created_at?:string},Partial<{listing_id:string;storage_path:string;alt_text:string;sort_order:number;is_cover:boolean}>,[{foreignKeyName:'listing_images_listing_id_fkey';columns:['listing_id'];isOneToOne:false;referencedRelation:'listings';referencedColumns:['id']}]>;
  enquiries:Table<{id:string;listing_id:string|null;name:string;phone:string|null;email:string|null;message:string;preferred_contact:'phone'|'email'|'whatsapp';status:'new'|'contacted'|'inspection_arranged'|'closed'|'spam';consent_at:string;created_at:string;updated_at:string},{name:string;message:string;preferred_contact:'phone'|'email'|'whatsapp';consent_at:string;listing_id?:string|null;phone?:string|null;email?:string|null;status?:'new'|'contacted'|'inspection_arranged'|'closed'|'spam';id?:string;created_at?:string;updated_at?:string}>;
};Views:{[_ in never]:never};Functions:{[_ in never]:never};Enums:{listing_category:'property'|'vehicle';listing_purpose:'rent'|'sale'|'short_let';listing_status:'draft'|'published'|'under_offer'|'rented'|'sold'|'archived'|'unavailable';enquiry_status:'new'|'contacted'|'inspection_arranged'|'closed'|'spam';preferred_contact:'phone'|'email'|'whatsapp'};CompositeTypes:{[_ in never]:never}}};

